apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: somandens
  name: somandens
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/somandens
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: somandens
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: somandens
    spec:
      containers:
      - image: gcr.io/somandenscloudapp/github.com/somanden/kubernetesworkshop21:cf11a54d224e3b12e5be6a6ef54047c2850c5ccf
        imagePullPolicy: IfNotPresent
        name: somandens
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: somandens
  name: somandens
  selfLink: /api/v1/namespaces/default/services/somandens
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31194
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: somandens
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
